/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameNewRouteImport } from './routes/game.new'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameNewRoute = GameNewRouteImport.update({
  id: '/game/new',
  path: '/game/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/profile': typeof ProfileRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/game/new': typeof GameNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/profile': typeof ProfileRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/game/new': typeof GameNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/profile': typeof ProfileRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/game/new': typeof GameNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-found'
    | '/profile'
    | '/demo/tanstack-query'
    | '/game/$gameId'
    | '/game/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/not-found'
    | '/profile'
    | '/demo/tanstack-query'
    | '/game/$gameId'
    | '/game/new'
  id:
    | '__root__'
    | '/'
    | '/not-found'
    | '/profile'
    | '/demo/tanstack-query'
    | '/game/$gameId'
    | '/game/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  ProfileRoute: typeof ProfileRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  GameGameIdRoute: typeof GameGameIdRoute
  GameNewRoute: typeof GameNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/new': {
      id: '/game/new'
      path: '/game/new'
      fullPath: '/game/new'
      preLoaderRoute: typeof GameNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  ProfileRoute: ProfileRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  GameGameIdRoute: GameGameIdRoute,
  GameNewRoute: GameNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
