const games: Array<Game> = [
  /* Arcade Games */
  {
    id: '6',
    name: 'Flabby Physics',
    poster: '/games_images/flappy_physics.png',
    flashFile: '/games/flabby_physics.swf',
    description: 'Test your luck and skill in this poker game.',
    featured: true,
    categories: ['arcade'],
    type: 'flash',
    isMobileFriendly: false,
  },
  {
    id: '25',
    name: 'Pacman',
    poster: '/games_images/pacman.png',
    flashFile: '/games/pacman.swf',
    description: 'Test your luck and skill in this poker game.',
    categories: ['arcade'],
    type: 'flash',
    featured: true,
    isMobileFriendly: false,
  },
  {
    id: '18',
    name: 'Missile',
    poster: '/games_images/missile.png',
    flashFile: '/games/Missile.swf',
    description: 'Test your luck and skill in this poker game.',
    featured: true,
    categories: ['arcade'],
    type: 'flash',
    isMobileFriendly: true,
  },
  {
    id: '26',
    name: 'Santa and the Lost Gifts',
    poster: '/games_images/santalost.png',
    flashFile: '/games/santalost.swf',
    description: 'Test your luck and skill in this poker game.',
    categories: ['arcade'],
    type: 'flash',
    featured: true,
    isMobileFriendly: false,
  },
  {
    id: '17',
    name: 'Ice Punch',
    poster: '/games_images/ice_punch.png',
    flashFile: '/games/Ice Punch.swf',
    description: 'Test your luck and skill in this poker game.',
    categories: ['arcade'],
    type: 'flash',
    isMobileFriendly: true,
  },

  /* Casino */
  {
    id: '0',
    name: '4 Table Poker',
    poster: '/games_images/poker.png',
    flashFile: '/games/POKER-FACE-UP.swf',
    description: 'Test your luck and skill in this poker game.',
    featured: true,
    categories: ['casino', 'featured'],
    type: 'flash',
    isMobileFriendly: true,
  },

  /* Adventure */
  {
    id: '16',
    name: 'Get Lost',
    poster: '/games_images/get_lost.png',
    flashFile: '/games/Get Lost.swf',
    description: 'Test your luck and skill in this poker game.',
    categories: ['adventure'],
    type: 'flash',
    isMobileFriendly: false,
  },

  /* Action */
  {
    id: '13',
    name: 'Age of War',
    poster: '/games_images/age_of_war.png',
    flashFile: '/games/Age_of_War.swf',
    description: 'Test your luck and skill in this poker game.',
    categories: ['action'],
    type: 'flash',
    isMobileFriendly: true,
  },

  /* Race */
  {
    id: '27',
    name: 'Pumpkin Head Rider',
    poster: '/games_images/pumpkin-rider.png',
    flashFile: '/games/pumpkin-rider.swf',
    description: 'Test your luck and skill in this poker game.',
    featured: true,
    categories: ['racing'],
    type: 'flash',
    isMobileFriendly: false,
  },
  {
    id: '20',
    name: 'Coaster Racer',
    poster: '/games_images/coaster_racer.png',
    flashFile: '/games/coaster-racer-714079f9.swf',
    description: 'Test your luck and skill in this poker game.',
    featured: true,
    categories: ['racing'],
    type: 'flash',
    isMobileFriendly: false,
  },
  {
    id: '21',
    name: 'Flash Racer',
    poster: '/games_images/flash_racer.png',
    flashFile: '/games/flash-racer-1321817f.swf',
    description: 'Test your luck and skill in this poker game.',
    categories: ['racing'],
    type: 'flash',
    isMobileFriendly: false,
  },
  {
    id: '10',
    name: 'Race Walk',
    poster: '/games_images/racewalk.png',
    flashFile: '/games/racewalk.swf',
    description: 'Test your luck and skill in this poker game.',
    categories: ['racing'],
    type: 'flash',
    isMobileFriendly: false,
  },

  /* Other */
  {
    id: '14',
    name: 'Dice Wars',
    poster: '/games_images/dice_wars.png',
    flashFile: '/games/Dice-Wars.swf',
    description: 'Test your luck and skill in this poker game.',
    categories: ['other'],
    type: 'flash',
    isMobileFriendly: true,
  },

  /* Partner Games */
  {
    id: '24',
    name: 'Slow Roads',
    poster: '/games_images/slow_roads.png',
    flashFile: 'https://slowroads.io',
    description: 'Slow Roads',
    featured: true,
    categories: ['partner'],
    type: 'iframe',
    isMobileFriendly: true,
  },
  {
    id: '23',
    name: 'Smash Karts',
    poster: '/games_images/smash_kart.png',
    flashFile: 'https://smashkarts.io/',
    description: 'Smash Karts',
    featured: true,
    categories: ['partner'],
    type: 'iframe',
    isMobileFriendly: true,
  },
]

export const sampleGames: Array<Game> = [...games]
